from __future__ import annotations

from collections.abc import Callable, Sequence
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from app.domain.entities.agent import Agent
from app.domain.entities.exam_session import ExamSession
from app.domain.entities.operations import AuditEvent, Command, Incident, TelemetryEvent
from app.domain.entities.session_workstation import SessionWorkstation
from app.domain.services.policy_profiles import PolicyProfileDefinition


class AgentRepository(Protocol):
    def add(self, agent: Agent) -> None: ...
    def get(self, agent_id: str) -> Agent: ...
    def find(self, agent_id: str) -> Agent | None: ...
    def save(self, agent: Agent) -> None: ...
    def list_all(self) -> list[Agent]: ...


class SessionRepository(Protocol):
    def add(self, session: ExamSession) -> None: ...
    def get(self, session_id: str) -> ExamSession: ...
    def save(self, session: ExamSession) -> None: ...
    def list_all(self) -> list[ExamSession]: ...


class SessionWorkstationRepository(Protocol):
    def assign(self, assignment: SessionWorkstation) -> None: ...
    def assign_many(self, assignments: Sequence[SessionWorkstation]) -> None: ...
    def list_for_session(self, session_id: str) -> list[SessionWorkstation]: ...


class CommandRepository(Protocol):
    def add_many(self, commands: Sequence[Command]) -> None: ...
    def get(self, command_id: str) -> Command: ...
    def save(self, command: Command) -> None: ...
    def available_for_target(self, target_id: str, at: datetime) -> list[Command]: ...


class PolicyProfileRepository(Protocol):
    def add(self, profile: PolicyProfileDefinition) -> None: ...
    def get(self, profile_id: str) -> PolicyProfileDefinition: ...
    def find(self, profile_id: str) -> PolicyProfileDefinition | None: ...
    def save(self, profile: PolicyProfileDefinition) -> None: ...
    def delete(self, profile_id: str) -> None: ...
    def list_all(self) -> list[PolicyProfileDefinition]: ...


class TelemetryRepository(Protocol):
    def add(self, event: TelemetryEvent) -> None: ...
    def list_for_session(self, session_id: str) -> list[TelemetryEvent]: ...


class IncidentRepository(Protocol):
    def add(self, incident: Incident) -> None: ...
    def list_for_session(self, session_id: str) -> list[Incident]: ...


class AuditRepository(Protocol):
    def append(
        self, session_id: str, actor: str, action: str, target: str, details: dict
    ) -> AuditEvent: ...
    def list_for_session(self, session_id: str) -> list[AuditEvent]: ...
    def verify_chain(self, session_id: str) -> bool: ...


class UnitOfWork(Protocol):
    agents: AgentRepository
    sessions: SessionRepository
    session_workstations: SessionWorkstationRepository
    commands: CommandRepository
    policy_profiles: PolicyProfileRepository
    telemetry: TelemetryRepository
    incidents: IncidentRepository
    audits: AuditRepository

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, exc_type, exc_value, traceback) -> bool | None: ...
    def commit(self) -> None: ...


UnitOfWorkFactory = Callable[[], AbstractContextManager[UnitOfWork]]
