import { SessionStatus, WorkstationStatus, PreflightStatus } from '@/src/domain';

export const SESSION_STATUS_LABELS: Record<SessionStatus, string> = {
  CREATED: 'Đã tạo',
  DEPLOYING: 'Đang triển khai',
  PREFLIGHT: 'Đang kiểm tra',
  READY: 'Sẵn sàng',
  DEGRADED: 'Cảnh báo',
  RUNNING: 'Đang thi',
  FINISHED: 'Đã kết thúc',
  RESTORING: 'Đang hoàn nguyên',
  NORMAL: 'Hoàn tất',
};

export const WORKSTATION_STATUS_LABELS: Record<WorkstationStatus, string> = {
  READY: 'Sẵn sàng',
  WARNING: 'Cảnh báo',
  FAILED: 'Lỗi',
  PENDING: 'Đang chờ',
};

export const PREFLIGHT_STATUS_LABELS: Record<PreflightStatus, string> = {
  PASSED: 'Đạt',
  WARNING: 'Cảnh báo',
  FAILED: 'Lỗi',
  PENDING: 'Đang chờ',
};

export const UI_LABELS = {
  actions: {
    cancel: 'Hủy',
    close: 'Đóng',
    retry: 'Thử lại',
    confirm: 'Xác nhận',
    save: 'Lưu',
    view: 'Xem',
    hide: 'Ẩn',
    filter: 'Lọc',
    inspect: 'Kiểm tra',
  },
  status: {
    ready: 'Sẵn sàng',
    warning: 'Cảnh báo',
    failed: 'Lỗi',
    pending: 'Đang chờ',
    passed: 'Đạt',
    created: 'Đã tạo',
    deploying: 'Đang triển khai',
    preflight: 'Kiểm tra',
    running: 'Đang thi',
  },
  session: {
    label: 'CA THI',
    sessions: 'Danh sách ca thi',
    detail: 'Chi tiết ca thi',
    refresh: 'Làm mới',
    deployPolicy: 'Triển khai chính sách',
    modifyPolicy: 'Sửa chính sách',
    startExam: 'Bắt đầu thi',
    forceStart: 'Bắt đầu cưỡng chế',
    activeExam: 'Đang thi',
    actions: 'Thao tác',
  },
  lifecycle: {
    title: 'VÒNG ĐỜI CA THI',
  },
  environment: {
    title: 'MÔI TRƯỜNG',
    room: 'Phòng',
    gateway: 'Gateway',
    workstations: 'máy trạm',
    totalWorkstations: 'máy trạm',
  },
  policy: {
    title: 'CHÍNH SÁCH BẢO MẬT',
    network: 'Mạng',
    usb: 'USB',
    strict: 'Nghiêm ngặt',
    acknowledged: 'Đã xác nhận',
    dispatching: 'Đang gửi',
    notDeployed: 'Chưa triển khai',
    details: 'Chi tiết →',
    hideDetails: 'Ẩn chi tiết',
    noPolicy: 'Chưa có chính sách',
    noPolicyDesc: 'Cần triển khai chính sách trước khi kiểm tra máy trạm.',
    deploy: 'Triển khai',
    targetGateway: 'Gateway đích',
    policyHash: 'Mã băm chính sách (Hash)',
    allowedProcesses: 'Tiến trình cho phép',
    lastAck: 'Xác nhận lần cuối',
  },
  workstations: {
    title: 'MÁY TRẠM',
    total: 'TỔNG',
    ready: 'SẴN SÀNG',
    warning: 'CẢNH BÁO',
    failed: 'LỖI',
    searchPlaceholder: 'Tìm mã (VD: PC01) hoặc IP...',
    clearFilter: 'Xóa bộ lọc',
    noMatch: 'Không tìm thấy máy trạm phù hợp.',
    page: 'Trang',
    of: 'trên',
    inspect: 'Kiểm tra',
  },
  workstation: {
    title: 'MÁY TRẠM',
    total: 'TỔNG',
    ready: 'SẴN SÀNG',
    warning: 'CẢNH BÁO',
    failed: 'LỖI',
    searchPlaceholder: 'Tìm mã (VD: PC01) hoặc IP...',
    clearFilter: 'Xóa bộ lọc',
    noMatch: 'Không tìm thấy máy trạm phù hợp.',
    page: 'Trang',
    of: 'trên',
    inspect: 'Kiểm tra',
  },
  activity: {
    title: 'HOẠT ĐỘNG GẦN ĐÂY',
    events: 'sự kiện',
    view: 'Xem',
    hide: 'Ẩn',
    empty: '[--:--:--] HỆ THỐNG Đang chờ bản tin từ bộ điều phối lệnh...',
    listening: 'Hệ thống đang chờ bản tin từ bộ điều phối...',
  },
  nav: {
    dashboard: 'Tổng quan',
    liveSessions: 'Danh sách ca thi',
    newSession: 'Tạo ca thi',
    policies: 'Chính sách bảo mật',
    monitoring: 'Giám sát',
    operations: 'Vận hành',
  },
} as const;
